- demo/app-root.ts
- index.ts
- package-lock.json
- package.json
- src/models/aggregation.ts
- src/search-params.ts
- test/search-params.test.ts
There are certain fields in the aggregations (facets), particularly the year histogram facet where the data is different depending on how it is requested: "simple" facets vs json-style "advanced" facets. This adds support for both formats so we can request the year histogram independently from the other facets.
> Add support for simple aggregations

- src/models/file.ts
ex. https://archive.org/metadata/cd_taylor-swift_taylor-swift 
has file info with a list of external_identifiers
```
{
"name": "disc1/01. Taylor Swift - Tim McGraw.flac",
"source": "original",
"mtime": "1515314129",
"size": "28581095",
"md5": "748e4988def50a1d271007d9855665fa",
"crc32": "4873b495",
"sha1": "f65a750cf86b87f43d4117e87f8b0271744b3036",
"format": "Flac",
"length": "234.55",
"height": "640",
"width": "640",
"private": "true",
"album": "Taylor Swift",
"comment": "https://archive.org/details/cd_taylor-swift_taylor-swift",
"title": "Tim McGraw",
"artist": "Taylor Swift",
"track": "1",
"external-identifier": [
"urn:acoustid:c1b6f24a-d9c3-400f-80d1-2c13d9a47bfd",
"urn:mb_recording_id:4bea9dc0-11d3-4dc1-936b-73361da356eb",
"urn:spotify:track:0Om9WAB5RS09L80DyOfTNa", …
```
> file.external_identifer can be an array of strings

- package-lock.json
- package.json
- src/models/metadata.ts
Just adding a getter for text snippets on the Metadata model, to prepare for FTS integration.
Bumps version to 0.3.5
> Add snippets field to metadata model

- src/models/hit-types/item-hit.ts
- src/models/hit-types/text-hit.ts
- test/models/hit-types/item-hit.test.ts
- test/models/hit-types/text-hit.test.ts
The PPS hit schemas have been updated to include several fields that were previously missing: `addeddate`, `avg_rating`, `issue`, `item_count`, and `source`. This PR adds those to the search service hit types so that they are more readily available to consumers.
> WEBDEV-5516 Add new fields being returned by PPS

- demo/app-root.ts
- src/search-param-url-generator.ts
- src/search-params.ts
- test/search-backend/fulltext-search-backend.test.ts
- test/search-backend/metadata-search-backend.test.ts
- test/search-params.test.ts
The PPS now handles a `uid` parameter that is returned unmodified in the response, which can be used to determine whether responses should be ignored as obsolete (i.e., from a previous search). Our current strategy for this is to compare the current query with the one in each response’s client_parameters, but this is unreliable since in some cases the backend may alter those in a normalization step. The `uid`, in contrast, is guaranteed to be returned-as-received.
The PPS also has tentative support for a `client_url` param which should contain the full URL that the search is originating from, to aid in debugging issues that arise on the PPS end.
This PR adds support for both of these params to the search service.
> WEBDEV-5544 Add `uid` and `client_url` PPS params

- src/models/hit-types/item-hit.ts
- test/models/hit-types/item-hit.test.ts
Until recently, the PPS only provided `publicdate` and `reviewdate` fields for full-text search hits, not metadata hits. However, these fields are now present on responses for both types of hits.
This PR adds those two fields to the metadata (ItemHit) model to make them readily accessible to clients.
> WEBDEV-5749 Add publicdate and reviewdate fields to item hit model

- src/search-backend/base-search-backend.ts
Errors from the Page Production Service (PPS) backend have a slightly different structure than the ones that we used to receive from advancedsearch.php. This PR updates the error handling flow to account for this and ensure error messages are properly passed along to the caller.
> WEBDEV-5767 Conform error handler to PPS error structure

- src/models/aggregation.ts
- src/responses/search-request-params.ts
- src/search-backend/base-search-backend.ts
- src/search-backend/search-backend-options.ts
- src/search-service.ts
- test/models/aggregation.test.ts
- test/search-backend/fulltext-search-backend.test.ts
- test/search-backend/metadata-search-backend.test.ts
This PR adds support for the `caching` and `verbose` options on search service backend instances.
The `caching` option indicates flags for the PPS to modify how the request interacts with the cache. The `verbose` option indicates whether all responses from the backend should be logged to the console (with some elements truncated, such as the `hits` array and aggregation buckets).
Both options are passed through automatically from the page URL if present and not otherwise specified.
> WEBDEV-5797 Add `caching` and `verbose` options

- src/responses/search-response-details.ts
- test/responses/search-response-details.test.ts
This PR adds a `collectionTitles` property to `SearchResponseDetails` objects, which optionally contains any collection titles object found on the response. The PPS has recently been upgraded to include such an object on hits/aggregations requests, containing a mapping from any collection identifiers to their readable titles.
> WEBDEV-5842 Add `collectionTitles` property to match new PPS responses

- demo/app-root.ts
- src/search-param-url-generator.ts
- src/search-params.ts
- test/models/metadata.test.ts
This PR truncates the `client_url` param if it is longer than 400 characters (which should be more than enough for most debugging purposes), and omits the `client_url` param entirely if the query length exceeds 1000 characters. This is to allow more space within the URL length limit for long queries or requests with many filters.
> WEBDEV-6051 Limit length of `client_url` param and omit it entirely for very long queries

- index.ts
- src/responses/collection-extra-info.ts
The PPS now has an updated format for its `collection_extra_info`, with everything that used to be under the old `search_docs` branch now promoted up a level (since the client shouldn’t care where the metadata was stored).
This PR updates the search service models accordingly.
> WEBDEV-6207 Promote collection search docs to top-level of extra info

- src/responses/collection-extra-info.ts
The PPS uses `contributor_details` with singular contributor. Current search service field has an extra 's'.
> Fix a typo in contributor_details field

- src/search-backend/base-search-backend.ts
- test/search-backend/fulltext-search-backend.test.ts
- test/search-backend/metadata-search-backend.test.ts
Permits legacy-style caching params to be used on Offshoot pages (`reCache`, `noCache`, and the new `dontCache`), and aliases the `cacheDebug` param to have the behavior as `debugging`.
> WEBDEV-6399 Legacy caching params

- index.ts
- src/responses/search-response-session-context.ts
- src/responses/search-response.ts
Exposes the `session_context` branch of PPS responses on the response model returned from searches. Notably, this provides access to the `full_text_search_override` key needed to enable FTS on collections for priv'd users.
> WEBDEV-6697 Add `session_context` to response model

- index.ts
- src/models/hit-types/hit.ts
- src/responses/search-response-details.ts
- src/search-backend/radio-search-backend.ts
- src/search-service.ts
- src/search-type.ts
- test/responses/search-response-details.test.ts
- test/search-backend/radio-search-backend.test.ts
- test/search-service.test.ts
Adds a new search backend for requesting radio caption hits from the PPS, updating models to account for this new search type.
> WEBDEV-6909 Add radio search backend

- .github/workflows/ci.yml
Our existing means of uploading coverage reports to codecov has been deprecated and superseded by the `codecov-action` GH action. This PR updates our CI workflow to rely on the new action.
> Update CI to use newer codecov action

- src/models/hit-types/hit.ts
- src/models/hit-types/tv-clip-hit.ts
- src/responses/page-elements.ts
- src/responses/search-response-details.ts
- src/search-backend/federated-search-backend.ts
- src/search-service.ts
- src/search-type.ts
- test/models/hit-types/tv-clip-hit.test.ts
- test/responses/search-response-details.test.ts
- test/search-backend/federated-search-backend.test.ts
- test/search-service.test.ts
Adds a new search type (`SearchType.FEDERATED`) to the search service to fetch federated results from the new PPS endpoint. Intended to be used for search prototyping.
**Current endpoint service names in response:**
- Full text: `fts`
- TV: `tvs`
- Radio: `rcs`
- Whisper: `whisper`
**Accessing results:**
- `response.pageElements.fts.hits` --> a full raw `hits` object with totals, returned count, and an array of hits
- `response.federatedResults.fts` --> an array of hits correctly formatted as `TextHit`, `TVClipHit`, etc.
> WEBDEV-7033 Add federated search to search service

- src/responses/account-extra-info.ts
- test/responses/search-response-details.test.ts
Mirrors a PPS change adding the `is_archivist` property to the `account_extra_info` branch.
> WEBDEV-7310 Add is_archivist property to account info

- index.ts
- src/responses/page-elements.ts
- src/responses/search-response-details.ts
Adjusts the federated search responses to include the partitioned mediatype results in addition to the cross-service results.
> WEBDEV-7090 Add partitioned mediatypes to federated search results

- package-lock.json
- package.json
Version includes `item_count` field on TV hits and dependency upgrades.
> Bump version to v2.3.0

- src/models/aggregation.ts
- src/responses/search-response-details.ts
- test/models/aggregation.test.ts
- test/responses/search-response-details.test.ts
- Updates aggregation model to support new keys used by the `date_histogram` aggregation (which has month resolution, unlike `year_histogram`)
- Removes some old, unused keys from aggregation models
- Adds support for the `tv_channel_aliases` response branch containing channel-to-network name mappings
> WEBDEV-5427 Add support for `date_histogram` aggregations and TV channel aliases

- src/responses/search-response-session-context.ts
Adds the `has_any_priv_permissive`, `has_collection_priv`, and `pps_relevant_user_preferences` fields to the model for the session context branch of the PPS response.
> WEBDEV-7667 Add missing fields to session context model
